fix husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,42 +1,26 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo '🏗️👷 Pre Commit Tests: Linting + Type Checking 🏗️👷'
+echo '🏗️👷 Running Pre Commit Tests'
 
-# Check Prettier standards
-npm run check-format ||
+pnpm  check-format ||
 (
-    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
-            Prettier Check Failed. Run npm run format, add changes and try commit again.';
+    echo '⛔🤢🤮 Bad Formatting. Run pnpm format then commit'
     false;
 )
 
-# Check ESLint Standards
-npm run check-lint ||
+pnpm  check-lint ||
 (
-        echo '🏀👋😬 ESLint Check Failed!  
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+        echo '⛔🏀👋😬 ESLint Check Failed!'
         false; 
 )
 
 echo '✅ Linting passed successfully.'
-# Check tsconfig standards
-npm run check-types ||
+
+pnpm check-types ||
 (
-    echo '🥲🙃🥴 Failed Type check.'
+    echo '⛔😱🥴 Failed Type check.'
     false;
 )
 
 echo '✅ Type Chceking passed successfully.'
-# If everything passes... Now we can commit
-
-# echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
-# npm run build ||
-# (
-#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
-#             Next build failed: View the errors above to see why. 
-#     '
-#     false;
-# )
-
-# If everything passes... Now we can commit
